/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_roc(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_roc(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_roc(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


#include <stdint.h>		// Use the C99 official header


#include "roc.h"


static float *new_float() { 
  return (float *) calloc(1,sizeof(float)); 
}

static float *copy_float(float value) { 
  float *obj = (float *) calloc(1,sizeof(float));
  *obj = value;
  return obj; 
}

static void delete_float(float *obj) { 
  if (obj) free(obj); 
}

static void float_assign(float *obj, float value) {
  *obj = value;
}

static float float_value(float *obj) {
  return *obj;
}


static uint8_t *new_uint8_t() { 
  return (uint8_t *) calloc(1,sizeof(uint8_t)); 
}

static uint8_t *copy_uint8_t(uint8_t value) { 
  uint8_t *obj = (uint8_t *) calloc(1,sizeof(uint8_t));
  *obj = value;
  return obj; 
}

static void delete_uint8_t(uint8_t *obj) { 
  if (obj) free(obj); 
}

static void uint8_t_assign(uint8_t *obj, uint8_t value) {
  *obj = value;
}

static uint8_t uint8_t_value(uint8_t *obj) {
  return *obj;
}


static size_t *new_size_t() { 
  return (size_t *) calloc(1,sizeof(size_t)); 
}

static size_t *copy_size_t(size_t value) { 
  size_t *obj = (size_t *) calloc(1,sizeof(size_t));
  *obj = value;
  return obj; 
}

static void delete_size_t(size_t *obj) { 
  if (obj) free(obj); 
}

static void size_t_assign(size_t *obj, size_t value) {
  *obj = value;
}

static size_t size_t_value(size_t *obj) {
  return *obj;
}


static roc_gallery *new_roc_gallery() { 
  return (roc_gallery *) calloc(1,sizeof(roc_gallery)); 
}

static roc_gallery *copy_roc_gallery(roc_gallery value) { 
  roc_gallery *obj = (roc_gallery *) calloc(1,sizeof(roc_gallery));
  *obj = value;
  return obj; 
}

static void delete_roc_gallery(roc_gallery *obj) { 
  if (obj) free(obj); 
}

static void roc_gallery_assign(roc_gallery *obj, roc_gallery value) {
  *obj = value;
}

static roc_gallery roc_gallery_value(roc_gallery *obj) {
  return *obj;
}


static roc_host_id *new_roc_host_id() { 
  return (roc_host_id *) calloc(1,sizeof(roc_host_id)); 
}

static roc_host_id *copy_roc_host_id(roc_host_id value) { 
  roc_host_id *obj = (roc_host_id *) calloc(1,sizeof(roc_host_id));
  *obj = value;
  return obj; 
}

static void delete_roc_host_id(roc_host_id *obj) { 
  if (obj) free(obj); 
}

static void roc_host_id_assign(roc_host_id *obj, roc_host_id value) {
  *obj = value;
}

static roc_host_id roc_host_id_value(roc_host_id *obj) {
  return *obj;
}


static roc_similarity *new_roc_similarity() { 
  return (roc_similarity *) calloc(1,sizeof(roc_similarity)); 
}

static roc_similarity *copy_roc_similarity(roc_similarity value) { 
  roc_similarity *obj = (roc_similarity *) calloc(1,sizeof(roc_similarity));
  *obj = value;
  return obj; 
}

static void delete_roc_similarity(roc_similarity *obj) { 
  if (obj) free(obj); 
}

static void roc_similarity_assign(roc_similarity *obj, roc_similarity value) {
  *obj = value;
}

static roc_similarity roc_similarity_value(roc_similarity *obj) {
  return *obj;
}


static char *new_char_array(int nelements) { 
  return (char *) calloc(nelements,sizeof(char)); 
}

static void delete_char_array(char *ary) { 
  free(ary); 
}

static char char_array_getitem(char *ary, int index) {
    return ary[index];
}
static void char_array_setitem(char *ary, int index, char value) {
    ary[index] = value;
}


static roc_template *new_roc_template_array(int nelements) { 
  return (roc_template *) calloc(nelements,sizeof(roc_template)); 
}

static void delete_roc_template_array(roc_template *ary) { 
  free(ary); 
}

static roc_template roc_template_array_getitem(roc_template *ary, int index) {
    return ary[index];
}
static void roc_template_array_setitem(roc_template *ary, int index, roc_template value) {
    ary[index] = value;
}


static roc_similarity *new_roc_similarity_array(int nelements) { 
  return (roc_similarity *) calloc(nelements,sizeof(roc_similarity)); 
}

static void delete_roc_similarity_array(roc_similarity *ary) { 
  free(ary); 
}

static roc_similarity roc_similarity_array_getitem(roc_similarity *ary, int index) {
    return ary[index];
}
static void roc_similarity_array_setitem(roc_similarity *ary, int index, roc_similarity value) {
    ary[index] = value;
}


static roc_candidate *new_roc_candidate_array(int nelements) { 
  return (roc_candidate *) calloc(nelements,sizeof(roc_candidate)); 
}

static void delete_roc_candidate_array(roc_candidate *ary) { 
  free(ary); 
}

static roc_candidate roc_candidate_array_getitem(roc_candidate *ary, int index) {
    return ary[index];
}
static void roc_candidate_array_setitem(roc_candidate *ary, int index, roc_candidate value) {
    ary[index] = value;
}


static roc_person_id *new_roc_person_id_array(int nelements) { 
  return (roc_person_id *) calloc(nelements,sizeof(roc_person_id)); 
}

static void delete_roc_person_id_array(roc_person_id *ary) { 
  free(ary); 
}

static roc_person_id roc_person_id_array_getitem(roc_person_id *ary, int index) {
    return ary[index];
}
static void roc_person_id_array_setitem(roc_person_id *ary, int index, roc_person_id value) {
    ary[index] = value;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_new_float() {
  void * jresult ;
  float *result = 0 ;
  
  result = (float *)new_float();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_copy_float(float jarg1) {
  void * jresult ;
  float arg1 ;
  float *result = 0 ;
  
  arg1 = (float)jarg1; 
  result = (float *)copy_float(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_float(void * jarg1) {
  float *arg1 = (float *) 0 ;
  
  arg1 = (float *)jarg1; 
  delete_float(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_float_assign(void * jarg1, float jarg2) {
  float *arg1 = (float *) 0 ;
  float arg2 ;
  
  arg1 = (float *)jarg1; 
  arg2 = (float)jarg2; 
  float_assign(arg1,arg2);
}


SWIGEXPORT float SWIGSTDCALL CSharp_float_value(void * jarg1) {
  float jresult ;
  float *arg1 = (float *) 0 ;
  float result;
  
  arg1 = (float *)jarg1; 
  result = (float)float_value(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_uint8_t() {
  void * jresult ;
  uint8_t *result = 0 ;
  
  result = (uint8_t *)new_uint8_t();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_copy_uint8_t(unsigned char jarg1) {
  void * jresult ;
  uint8_t arg1 ;
  uint8_t *result = 0 ;
  
  arg1 = (uint8_t)jarg1; 
  result = (uint8_t *)copy_uint8_t(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_uint8_t(void * jarg1) {
  uint8_t *arg1 = (uint8_t *) 0 ;
  
  arg1 = (uint8_t *)jarg1; 
  delete_uint8_t(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uint8_t_assign(void * jarg1, unsigned char jarg2) {
  uint8_t *arg1 = (uint8_t *) 0 ;
  uint8_t arg2 ;
  
  arg1 = (uint8_t *)jarg1; 
  arg2 = (uint8_t)jarg2; 
  uint8_t_assign(arg1,arg2);
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_uint8_t_value(void * jarg1) {
  unsigned char jresult ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  uint8_t result;
  
  arg1 = (uint8_t *)jarg1; 
  result = (uint8_t)uint8_t_value(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_size_t() {
  void * jresult ;
  size_t *result = 0 ;
  
  result = (size_t *)new_size_t();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_copy_size_t(unsigned long jarg1) {
  void * jresult ;
  size_t arg1 ;
  size_t *result = 0 ;
  
  arg1 = (size_t)jarg1; 
  result = (size_t *)copy_size_t(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_size_t(void * jarg1) {
  size_t *arg1 = (size_t *) 0 ;
  
  arg1 = (size_t *)jarg1; 
  delete_size_t(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_size_t_assign(void * jarg1, unsigned long jarg2) {
  size_t *arg1 = (size_t *) 0 ;
  size_t arg2 ;
  
  arg1 = (size_t *)jarg1; 
  arg2 = (size_t)jarg2; 
  size_t_assign(arg1,arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_size_t_value(void * jarg1) {
  unsigned long jresult ;
  size_t *arg1 = (size_t *) 0 ;
  size_t result;
  
  arg1 = (size_t *)jarg1; 
  result = size_t_value(arg1);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_roc_gallery() {
  void * jresult ;
  roc_gallery *result = 0 ;
  
  result = (roc_gallery *)new_roc_gallery();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_copy_roc_gallery(void * jarg1) {
  void * jresult ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_gallery *result = 0 ;
  
  arg1 = (roc_gallery)jarg1; 
  result = (roc_gallery *)copy_roc_gallery(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_roc_gallery(void * jarg1) {
  roc_gallery *arg1 = (roc_gallery *) 0 ;
  
  arg1 = (roc_gallery *)jarg1; 
  delete_roc_gallery(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_gallery_assign(void * jarg1, void * jarg2) {
  roc_gallery *arg1 = (roc_gallery *) 0 ;
  roc_gallery arg2 = (roc_gallery) 0 ;
  
  arg1 = (roc_gallery *)jarg1; 
  arg2 = (roc_gallery)jarg2; 
  roc_gallery_assign(arg1,arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_roc_gallery_value(void * jarg1) {
  void * jresult ;
  roc_gallery *arg1 = (roc_gallery *) 0 ;
  roc_gallery result;
  
  arg1 = (roc_gallery *)jarg1; 
  result = (roc_gallery)roc_gallery_value(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_roc_host_id() {
  void * jresult ;
  roc_host_id *result = 0 ;
  
  result = (roc_host_id *)new_roc_host_id();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_copy_roc_host_id(char * jarg1) {
  void * jresult ;
  roc_host_id arg1 = (roc_host_id) 0 ;
  roc_host_id *result = 0 ;
  
  arg1 = (roc_host_id)jarg1; 
  result = (roc_host_id *)copy_roc_host_id((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_roc_host_id(void * jarg1) {
  roc_host_id *arg1 = (roc_host_id *) 0 ;
  
  arg1 = (roc_host_id *)jarg1; 
  delete_roc_host_id((char const **)arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_host_id_assign(void * jarg1, char * jarg2) {
  roc_host_id *arg1 = (roc_host_id *) 0 ;
  roc_host_id arg2 = (roc_host_id) 0 ;
  
  arg1 = (roc_host_id *)jarg1; 
  arg2 = (roc_host_id)jarg2; 
  roc_host_id_assign((char const **)arg1,(char const *)arg2);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_host_id_value(void * jarg1) {
  char * jresult ;
  roc_host_id *arg1 = (roc_host_id *) 0 ;
  roc_host_id result;
  
  arg1 = (roc_host_id *)jarg1; 
  result = (roc_host_id)roc_host_id_value((char const **)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_roc_similarity() {
  void * jresult ;
  roc_similarity *result = 0 ;
  
  result = (roc_similarity *)new_roc_similarity();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_copy_roc_similarity(float jarg1) {
  void * jresult ;
  roc_similarity arg1 ;
  roc_similarity *result = 0 ;
  
  arg1 = (roc_similarity)jarg1; 
  result = (roc_similarity *)copy_roc_similarity(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_roc_similarity(void * jarg1) {
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  
  arg1 = (roc_similarity *)jarg1; 
  delete_roc_similarity(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_similarity_assign(void * jarg1, float jarg2) {
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  roc_similarity arg2 ;
  
  arg1 = (roc_similarity *)jarg1; 
  arg2 = (roc_similarity)jarg2; 
  roc_similarity_assign(arg1,arg2);
}


SWIGEXPORT float SWIGSTDCALL CSharp_roc_similarity_value(void * jarg1) {
  float jresult ;
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  roc_similarity result;
  
  arg1 = (roc_similarity *)jarg1; 
  result = (roc_similarity)roc_similarity_value(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_new_char_array(int jarg1) {
  char * jresult ;
  int arg1 ;
  char *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (char *)new_char_array(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_char_array(char * jarg1) {
  char *arg1 = (char *) 0 ;
  
  arg1 = (char *)jarg1; 
  delete_char_array(arg1);
}


SWIGEXPORT char SWIGSTDCALL CSharp_char_array_getitem(char * jarg1, int jarg2) {
  char jresult ;
  char *arg1 = (char *) 0 ;
  int arg2 ;
  char result;
  
  arg1 = (char *)jarg1; 
  arg2 = (int)jarg2; 
  result = (char)char_array_getitem(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_char_array_setitem(char * jarg1, int jarg2, char jarg3) {
  char *arg1 = (char *) 0 ;
  int arg2 ;
  char arg3 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (char)jarg3; 
  char_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_roc_template_array(int jarg1) {
  void * jresult ;
  int arg1 ;
  roc_template *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (roc_template *)new_roc_template_array(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_roc_template_array(void * jarg1) {
  roc_template *arg1 = (roc_template *) 0 ;
  
  arg1 = (roc_template *)jarg1; 
  delete_roc_template_array(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_roc_template_array_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  roc_template *arg1 = (roc_template *) 0 ;
  int arg2 ;
  roc_template result;
  
  arg1 = (roc_template *)jarg1; 
  arg2 = (int)jarg2; 
  result = roc_template_array_getitem(arg1,arg2);
  {
    roc_template * resultptr = (roc_template *) malloc(sizeof(roc_template));
    memmove(resultptr, &result, sizeof(roc_template));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_array_setitem(void * jarg1, int jarg2, void * jarg3) {
  roc_template *arg1 = (roc_template *) 0 ;
  int arg2 ;
  roc_template arg3 ;
  roc_template *argp3 ;
  
  arg1 = (roc_template *)jarg1; 
  arg2 = (int)jarg2; 
  argp3 = (roc_template *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_template", 0);
    return ;
  }
  arg3 = *argp3; 
  roc_template_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_roc_similarity_array(int jarg1) {
  void * jresult ;
  int arg1 ;
  roc_similarity *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (roc_similarity *)new_roc_similarity_array(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_roc_similarity_array(void * jarg1) {
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  
  arg1 = (roc_similarity *)jarg1; 
  delete_roc_similarity_array(arg1);
}


SWIGEXPORT float SWIGSTDCALL CSharp_roc_similarity_array_getitem(void * jarg1, int jarg2) {
  float jresult ;
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  int arg2 ;
  roc_similarity result;
  
  arg1 = (roc_similarity *)jarg1; 
  arg2 = (int)jarg2; 
  result = (roc_similarity)roc_similarity_array_getitem(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_similarity_array_setitem(void * jarg1, int jarg2, float jarg3) {
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  int arg2 ;
  roc_similarity arg3 ;
  
  arg1 = (roc_similarity *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (roc_similarity)jarg3; 
  roc_similarity_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_roc_candidate_array(int jarg1) {
  void * jresult ;
  int arg1 ;
  roc_candidate *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (roc_candidate *)new_roc_candidate_array(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_roc_candidate_array(void * jarg1) {
  roc_candidate *arg1 = (roc_candidate *) 0 ;
  
  arg1 = (roc_candidate *)jarg1; 
  delete_roc_candidate_array(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_roc_candidate_array_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  roc_candidate *arg1 = (roc_candidate *) 0 ;
  int arg2 ;
  roc_candidate result;
  
  arg1 = (roc_candidate *)jarg1; 
  arg2 = (int)jarg2; 
  result = roc_candidate_array_getitem(arg1,arg2);
  {
    roc_candidate * resultptr = (roc_candidate *) malloc(sizeof(roc_candidate));
    memmove(resultptr, &result, sizeof(roc_candidate));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_candidate_array_setitem(void * jarg1, int jarg2, void * jarg3) {
  roc_candidate *arg1 = (roc_candidate *) 0 ;
  int arg2 ;
  roc_candidate arg3 ;
  roc_candidate *argp3 ;
  
  arg1 = (roc_candidate *)jarg1; 
  arg2 = (int)jarg2; 
  argp3 = (roc_candidate *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_candidate", 0);
    return ;
  }
  arg3 = *argp3; 
  roc_candidate_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_roc_person_id_array(int jarg1) {
  void * jresult ;
  int arg1 ;
  roc_person_id *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (roc_person_id *)new_roc_person_id_array(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_roc_person_id_array(void * jarg1) {
  roc_person_id *arg1 = (roc_person_id *) 0 ;
  
  arg1 = (roc_person_id *)jarg1; 
  delete_roc_person_id_array(arg1);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_roc_person_id_array_getitem(void * jarg1, int jarg2) {
  unsigned int jresult ;
  roc_person_id *arg1 = (roc_person_id *) 0 ;
  int arg2 ;
  roc_person_id result;
  
  arg1 = (roc_person_id *)jarg1; 
  arg2 = (int)jarg2; 
  result = (roc_person_id)roc_person_id_array_getitem(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_person_id_array_setitem(void * jarg1, int jarg2, unsigned int jarg3) {
  roc_person_id *arg1 = (roc_person_id *) 0 ;
  int arg2 ;
  roc_person_id arg3 ;
  
  arg1 = (roc_person_id *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (roc_person_id)jarg3; 
  roc_person_id_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_ROC_VERSION_MAJOR_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ROC_VERSION_MINOR_get() {
  int jresult ;
  int result;
  
  result = (int)(7);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ROC_VERSION_PATCH_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_ROC_VERSION_STRING_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("1.7.0");
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_ensure(char * jarg1) {
  roc_error arg1 = (roc_error) 0 ;
  
  arg1 = (roc_error)jarg1; 
  roc_ensure((char const *)arg1);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_initialize(char * jarg1) {
  char * jresult ;
  char *arg1 = (char *) 0 ;
  roc_error result;
  
  arg1 = (char *)jarg1; 
  result = (roc_error)roc_initialize((char const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_finalize() {
  char * jresult ;
  roc_error result;
  
  result = (roc_error)roc_finalize();
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_get_host_id(void * jarg1) {
  char * jresult ;
  roc_host_id *arg1 = (roc_host_id *) 0 ;
  roc_error result;
  
  arg1 = (roc_host_id *)jarg1; 
  result = (roc_error)roc_get_host_id((char const **)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_free_host_id(char * jarg1) {
  char * jresult ;
  roc_host_id arg1 = (roc_host_id) 0 ;
  roc_error result;
  
  arg1 = (roc_host_id)jarg1; 
  result = (roc_error)roc_free_host_id((char const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_image_data_set(void * jarg1, void * jarg2) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  arg1 = (struct roc_image *)jarg1; 
  arg2 = (uint8_t *)jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_roc_image_data_get(void * jarg1) {
  void * jresult ;
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  uint8_t *result = 0 ;
  
  arg1 = (struct roc_image *)jarg1; 
  result = (uint8_t *) ((arg1)->data);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_image_width_set(void * jarg1, unsigned long jarg2) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct roc_image *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->width = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_roc_image_width_get(void * jarg1) {
  unsigned long jresult ;
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t result;
  
  arg1 = (struct roc_image *)jarg1; 
  result =  ((arg1)->width);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_image_height_set(void * jarg1, unsigned long jarg2) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct roc_image *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->height = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_roc_image_height_get(void * jarg1) {
  unsigned long jresult ;
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t result;
  
  arg1 = (struct roc_image *)jarg1; 
  result =  ((arg1)->height);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_image_step_set(void * jarg1, unsigned long jarg2) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct roc_image *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->step = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_roc_image_step_get(void * jarg1) {
  unsigned long jresult ;
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t result;
  
  arg1 = (struct roc_image *)jarg1; 
  result =  ((arg1)->step);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_image_color_space_set(void * jarg1, int jarg2) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  roc_color_space arg2 ;
  
  arg1 = (struct roc_image *)jarg1; 
  arg2 = (roc_color_space)jarg2; 
  if (arg1) (arg1)->color_space = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_roc_image_color_space_get(void * jarg1) {
  int jresult ;
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  roc_color_space result;
  
  arg1 = (struct roc_image *)jarg1; 
  result = (roc_color_space) ((arg1)->color_space);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_roc_image() {
  void * jresult ;
  struct roc_image *result = 0 ;
  
  result = (struct roc_image *)calloc(1, sizeof(struct roc_image));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_roc_image(void * jarg1) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  
  arg1 = (struct roc_image *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_free_image(void * jarg1) {
  char * jresult ;
  roc_image arg1 ;
  roc_image *argp1 ;
  roc_error result;
  
  argp1 = (roc_image *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_image", 0);
    return 0;
  }
  arg1 = *argp1; 
  result = (roc_error)roc_free_image(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_read_image(char * jarg1, int jarg2, void * jarg3) {
  char * jresult ;
  char *arg1 = (char *) 0 ;
  roc_color_space arg2 ;
  roc_image *arg3 = (roc_image *) 0 ;
  roc_error result;
  
  arg1 = (char *)jarg1; 
  arg2 = (roc_color_space)jarg2; 
  arg3 = (roc_image *)jarg3; 
  result = (roc_error)roc_read_image((char const *)arg1,arg2,arg3);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_decode_image(unsigned long jarg1, void * jarg2, int jarg3, void * jarg4) {
  char * jresult ;
  size_t arg1 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  roc_color_space arg3 ;
  roc_image *arg4 = (roc_image *) 0 ;
  roc_error result;
  
  arg1 = (size_t)jarg1; 
  arg2 = (uint8_t *)jarg2; 
  arg3 = (roc_color_space)jarg3; 
  arg4 = (roc_image *)jarg4; 
  result = (roc_error)roc_decode_image(arg1,(unsigned char const *)arg2,arg3,arg4);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_set_thumbnail_parameters(int jarg1, int jarg2, float jarg3, float jarg4) {
  char * jresult ;
  int arg1 ;
  int arg2 ;
  float arg3 ;
  float arg4 ;
  roc_error result;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  result = (roc_error)roc_set_thumbnail_parameters(arg1,arg2,arg3,arg4);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_preload(unsigned int jarg1) {
  char * jresult ;
  roc_algorithm_id arg1 ;
  roc_error result;
  
  arg1 = (roc_algorithm_id)jarg1; 
  result = (roc_error)roc_preload(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_landmarks_to_face(float jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, void * jarg7, void * jarg8, void * jarg9, void * jarg10) {
  char * jresult ;
  float arg1 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  float arg6 ;
  float *arg7 = (float *) 0 ;
  float *arg8 = (float *) 0 ;
  float *arg9 = (float *) 0 ;
  float *arg10 = (float *) 0 ;
  roc_error result;
  
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  arg5 = (float)jarg5; 
  arg6 = (float)jarg6; 
  arg7 = (float *)jarg7; 
  arg8 = (float *)jarg8; 
  arg9 = (float *)jarg9; 
  arg10 = (float *)jarg10; 
  result = (roc_error)roc_landmarks_to_face(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ROC_NO_TIMESTAMP_get() {
  int jresult ;
  int result;
  
  result = (int)(0xFFFFFFFF);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ROC_UNKNOWN_PERSON_get() {
  int jresult ;
  int result;
  
  result = (int)(0xFFFFFFFF);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_algorithm_id_set(void * jarg1, unsigned int jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_algorithm_id arg2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (roc_algorithm_id)jarg2; 
  if (arg1) (arg1)->algorithm_id = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_roc_template_algorithm_id_get(void * jarg1) {
  unsigned int jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_algorithm_id result;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (roc_algorithm_id) ((arg1)->algorithm_id);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_timestamp_set(void * jarg1, void * jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_time arg2 ;
  roc_time *argp2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  argp2 = (roc_time *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_time", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->timestamp = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_roc_template_timestamp_get(void * jarg1) {
  void * jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_time result;
  
  arg1 = (struct roc_template *)jarg1; 
  result =  ((arg1)->timestamp);
  {
    roc_time * resultptr = (roc_time *) malloc(sizeof(roc_time));
    memmove(resultptr, &result, sizeof(roc_time));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_x_set(void * jarg1, int jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  int32_t arg2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (int32_t)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_roc_template_x_get(void * jarg1) {
  int jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  int32_t result;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (int32_t) ((arg1)->x);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_y_set(void * jarg1, int jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  int32_t arg2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (int32_t)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_roc_template_y_get(void * jarg1) {
  int jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  int32_t result;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (int32_t) ((arg1)->y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_width_set(void * jarg1, unsigned int jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t arg2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->width = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_roc_template_width_get(void * jarg1) {
  unsigned int jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t result;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (uint32_t) ((arg1)->width);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_height_set(void * jarg1, unsigned int jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t arg2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->height = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_roc_template_height_get(void * jarg1) {
  unsigned int jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t result;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (uint32_t) ((arg1)->height);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_confidence_set(void * jarg1, float jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  float arg2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->confidence = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_roc_template_confidence_get(void * jarg1) {
  float jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  float result;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (float) ((arg1)->confidence);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_person_id_set(void * jarg1, unsigned int jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_person_id arg2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (roc_person_id)jarg2; 
  if (arg1) (arg1)->person_id = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_roc_template_person_id_get(void * jarg1) {
  unsigned int jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_person_id result;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (roc_person_id) ((arg1)->person_id);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_md_size_set(void * jarg1, unsigned int jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t arg2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->md_size = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_roc_template_md_size_get(void * jarg1) {
  unsigned int jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t result;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (uint32_t) ((arg1)->md_size);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_fv_size_set(void * jarg1, unsigned int jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t arg2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->fv_size = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_roc_template_fv_size_get(void * jarg1) {
  unsigned int jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t result;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (uint32_t) ((arg1)->fv_size);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_tn_size_set(void * jarg1, unsigned int jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t arg2 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->tn_size = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_roc_template_tn_size_get(void * jarg1) {
  unsigned int jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t result;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (uint32_t) ((arg1)->tn_size);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_md_set(void * jarg1, char * jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->md = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->md, (const char *)arg2);
    } else {
      arg1->md = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_template_md_get(void * jarg1) {
  char * jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (char *) ((arg1)->md);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_fv_set(void * jarg1, void * jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (uint8_t *)jarg2; 
  if (arg1) (arg1)->fv = (uint8_t const *)arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_roc_template_fv_get(void * jarg1) {
  void * jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint8_t *result = 0 ;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (uint8_t *) ((arg1)->fv);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_template_tn_set(void * jarg1, void * jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  arg1 = (struct roc_template *)jarg1; 
  arg2 = (uint8_t *)jarg2; 
  if (arg1) (arg1)->tn = (uint8_t const *)arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_roc_template_tn_get(void * jarg1) {
  void * jresult ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint8_t *result = 0 ;
  
  arg1 = (struct roc_template *)jarg1; 
  result = (uint8_t *) ((arg1)->tn);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_roc_template() {
  void * jresult ;
  struct roc_template *result = 0 ;
  
  result = (struct roc_template *)calloc(1, sizeof(struct roc_template));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_roc_template(void * jarg1) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  
  arg1 = (struct roc_template *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_represent(void * jarg1, unsigned int jarg2, unsigned long jarg3, unsigned long jarg4, float jarg5, void * jarg6) {
  char * jresult ;
  roc_image arg1 ;
  roc_algorithm_id arg2 ;
  size_t arg3 ;
  size_t arg4 ;
  float arg5 ;
  roc_template *arg6 = (roc_template *) 0 ;
  roc_image *argp1 ;
  roc_error result;
  
  argp1 = (roc_image *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_image", 0);
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (roc_algorithm_id)jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (size_t)jarg4; 
  arg5 = (float)jarg5; 
  arg6 = (roc_template *)jarg6; 
  result = (roc_error)roc_represent(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_free_template(void * jarg1) {
  char * jresult ;
  roc_template *arg1 = (roc_template *) 0 ;
  roc_error result;
  
  arg1 = (roc_template *)jarg1; 
  result = (roc_error)roc_free_template(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_flatten(void * jarg1, void * jarg2) {
  char * jresult ;
  roc_template arg1 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  roc_template const *argp1 ;
  roc_error result;
  
  argp1 = (roc_template *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_template const", 0);
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (uint8_t *)jarg2; 
  result = (roc_error)roc_flatten(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_unflatten(void * jarg1, void * jarg2) {
  char * jresult ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  roc_template *arg2 = (roc_template *) 0 ;
  roc_error result;
  
  arg1 = (uint8_t *)jarg1; 
  arg2 = (roc_template *)jarg2; 
  result = (roc_error)roc_unflatten((unsigned char const *)arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_flattened_bytes(void * jarg1, void * jarg2) {
  char * jresult ;
  roc_template arg1 ;
  size_t *arg2 = (size_t *) 0 ;
  roc_template const *argp1 ;
  roc_error result;
  
  argp1 = (roc_template *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_template const", 0);
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (size_t *)jarg2; 
  result = (roc_error)roc_flattened_bytes(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_read_template(void * jarg1, void * jarg2) {
  char * jresult ;
  FILE *arg1 = (FILE *) 0 ;
  roc_template *arg2 = (roc_template *) 0 ;
  roc_error result;
  
  arg1 = (FILE *)jarg1; 
  arg2 = (roc_template *)jarg2; 
  result = (roc_error)roc_read_template(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_read_template_fd(int jarg1, void * jarg2) {
  char * jresult ;
  int arg1 ;
  roc_template *arg2 = (roc_template *) 0 ;
  roc_error result;
  
  arg1 = (int)jarg1; 
  arg2 = (roc_template *)jarg2; 
  result = (roc_error)roc_read_template_fd(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_write_template(void * jarg1, void * jarg2) {
  char * jresult ;
  FILE *arg1 = (FILE *) 0 ;
  roc_template arg2 ;
  roc_template const *argp2 ;
  roc_error result;
  
  arg1 = (FILE *)jarg1; 
  argp2 = (roc_template *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_template const", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (roc_error)roc_write_template(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_write_template_fd(int jarg1, void * jarg2) {
  char * jresult ;
  int arg1 ;
  roc_template arg2 ;
  roc_template const *argp2 ;
  roc_error result;
  
  arg1 = (int)jarg1; 
  argp2 = (roc_template *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_template const", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (roc_error)roc_write_template_fd(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_get_metadata(void * jarg1, char * jarg2, char * jarg3, unsigned long jarg4) {
  char * jresult ;
  roc_template arg1 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  size_t arg4 ;
  roc_template const *argp1 ;
  roc_error result;
  
  argp1 = (roc_template *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_template const", 0);
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  arg4 = (size_t)jarg4; 
  result = (roc_error)roc_get_metadata(arg1,(char const *)arg2,arg3,arg4);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_set_metadata(void * jarg1, char * jarg2, char * jarg3) {
  char * jresult ;
  roc_template *arg1 = (roc_template *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  roc_error result;
  
  arg1 = (roc_template *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (roc_error)roc_set_metadata(arg1,(char const *)arg2,(char const *)arg3);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_open_gallery(char * jarg1, void * jarg2, void * jarg3) {
  char * jresult ;
  roc_gallery_file arg1 = (roc_gallery_file) 0 ;
  roc_gallery *arg2 = (roc_gallery *) 0 ;
  roc_progress arg3 = (roc_progress) 0 ;
  roc_error result;
  
  arg1 = (roc_gallery_file)jarg1; 
  arg2 = (roc_gallery *)jarg2; 
  arg3 = (roc_progress)jarg3; 
  result = (roc_error)roc_open_gallery((char const *)arg1,arg2,arg3);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_temporary_gallery(void * jarg1) {
  char * jresult ;
  roc_gallery *arg1 = (roc_gallery *) 0 ;
  roc_error result;
  
  arg1 = (roc_gallery *)jarg1; 
  result = (roc_error)roc_temporary_gallery(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_enroll(void * jarg1, void * jarg2) {
  char * jresult ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_template arg2 ;
  roc_template const *argp2 ;
  roc_error result;
  
  arg1 = (roc_gallery)jarg1; 
  argp2 = (roc_template *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_template const", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (roc_error)roc_enroll(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_size(void * jarg1, void * jarg2) {
  char * jresult ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  size_t *arg2 = (size_t *) 0 ;
  roc_error result;
  
  arg1 = (roc_const_gallery)jarg1; 
  arg2 = (size_t *)jarg2; 
  result = (roc_error)roc_size((struct roc_gallery_type const *)arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ROC_INVALID_TEMPLATE_INDEX_get() {
  unsigned long jresult ;
  size_t result;
  
  result = (size_t)ROC_INVALID_TEMPLATE_INDEX;
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_at(void * jarg1, unsigned long jarg2, void * jarg3) {
  char * jresult ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  roc_template_index arg2 ;
  roc_template *arg3 = (roc_template *) 0 ;
  roc_error result;
  
  arg1 = (roc_const_gallery)jarg1; 
  arg2 = (roc_template_index)jarg2; 
  arg3 = (roc_template *)jarg3; 
  result = (roc_error)roc_at((struct roc_gallery_type const *)arg1,arg2,arg3);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_remove(void * jarg1, unsigned long jarg2) {
  char * jresult ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_template_index arg2 ;
  roc_error result;
  
  arg1 = (roc_gallery)jarg1; 
  arg2 = (roc_template_index)jarg2; 
  result = (roc_error)roc_remove(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_close_gallery(void * jarg1) {
  char * jresult ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_error result;
  
  arg1 = (roc_gallery)jarg1; 
  result = (roc_error)roc_close_gallery(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_template_limit(void * jarg1) {
  char * jresult ;
  size_t *arg1 = (size_t *) 0 ;
  roc_error result;
  
  arg1 = (size_t *)jarg1; 
  result = (roc_error)roc_template_limit(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_compare_templates(void * jarg1, void * jarg2, void * jarg3) {
  char * jresult ;
  roc_template arg1 ;
  roc_template arg2 ;
  roc_similarity *arg3 = (roc_similarity *) 0 ;
  roc_template const *argp1 ;
  roc_template const *argp2 ;
  roc_error result;
  
  argp1 = (roc_template *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_template const", 0);
    return 0;
  }
  arg1 = *argp1; 
  argp2 = (roc_template *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_template const", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (roc_similarity *)jarg3; 
  result = (roc_error)roc_compare_templates(arg1,arg2,arg3);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_compare_galleries(void * jarg1, void * jarg2, void * jarg3) {
  char * jresult ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  roc_const_gallery arg2 = (roc_const_gallery) 0 ;
  roc_similarity *arg3 = (roc_similarity *) 0 ;
  roc_error result;
  
  arg1 = (roc_const_gallery)jarg1; 
  arg2 = (roc_const_gallery)jarg2; 
  arg3 = (roc_similarity *)jarg3; 
  result = (roc_error)roc_compare_galleries((struct roc_gallery_type const *)arg1,(struct roc_gallery_type const *)arg2,arg3);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_candidate_index_set(void * jarg1, unsigned long jarg2) {
  struct roc_candidate *arg1 = (struct roc_candidate *) 0 ;
  roc_template_index arg2 ;
  
  arg1 = (struct roc_candidate *)jarg1; 
  arg2 = (roc_template_index)jarg2; 
  if (arg1) (arg1)->index = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_roc_candidate_index_get(void * jarg1) {
  unsigned long jresult ;
  struct roc_candidate *arg1 = (struct roc_candidate *) 0 ;
  roc_template_index result;
  
  arg1 = (struct roc_candidate *)jarg1; 
  result =  ((arg1)->index);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_roc_candidate_similarity_set(void * jarg1, float jarg2) {
  struct roc_candidate *arg1 = (struct roc_candidate *) 0 ;
  roc_similarity arg2 ;
  
  arg1 = (struct roc_candidate *)jarg1; 
  arg2 = (roc_similarity)jarg2; 
  if (arg1) (arg1)->similarity = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_roc_candidate_similarity_get(void * jarg1) {
  float jresult ;
  struct roc_candidate *arg1 = (struct roc_candidate *) 0 ;
  roc_similarity result;
  
  arg1 = (struct roc_candidate *)jarg1; 
  result = (roc_similarity) ((arg1)->similarity);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_roc_candidate() {
  void * jresult ;
  struct roc_candidate *result = 0 ;
  
  result = (struct roc_candidate *)calloc(1, sizeof(struct roc_candidate));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_roc_candidate(void * jarg1) {
  struct roc_candidate *arg1 = (struct roc_candidate *) 0 ;
  
  arg1 = (struct roc_candidate *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_search(void * jarg1, void * jarg2, unsigned long jarg3, float jarg4, void * jarg5) {
  char * jresult ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  roc_template arg2 ;
  size_t arg3 ;
  roc_similarity arg4 ;
  roc_candidate *arg5 = (roc_candidate *) 0 ;
  roc_template const *argp2 ;
  roc_error result;
  
  arg1 = (roc_const_gallery)jarg1; 
  argp2 = (roc_template *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_template const", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = (roc_similarity)jarg4; 
  arg5 = (roc_candidate *)jarg5; 
  result = (roc_error)roc_search((struct roc_gallery_type const *)arg1,arg2,arg3,arg4,arg5);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_knn(void * jarg1, void * jarg2, unsigned long jarg3, float jarg4, void * jarg5) {
  char * jresult ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  roc_const_gallery arg2 = (roc_const_gallery) 0 ;
  size_t arg3 ;
  roc_similarity arg4 ;
  roc_candidate *arg5 = (roc_candidate *) 0 ;
  roc_error result;
  
  arg1 = (roc_const_gallery)jarg1; 
  arg2 = (roc_const_gallery)jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (roc_similarity)jarg4; 
  arg5 = (roc_candidate *)jarg5; 
  result = (roc_error)roc_knn((struct roc_gallery_type const *)arg1,(struct roc_gallery_type const *)arg2,arg3,arg4,arg5);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_rerank(void * jarg1, unsigned long jarg2, void * jarg3) {
  char * jresult ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  size_t arg2 ;
  roc_candidate *arg3 = (roc_candidate *) 0 ;
  roc_error result;
  
  arg1 = (roc_const_gallery)jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (roc_candidate *)jarg3; 
  result = (roc_error)roc_rerank((struct roc_gallery_type const *)arg1,arg2,arg3);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_cluster(void * jarg1, unsigned long jarg2, void * jarg3, float jarg4) {
  char * jresult ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  size_t arg2 ;
  roc_candidate *arg3 = (roc_candidate *) 0 ;
  float arg4 ;
  roc_error result;
  
  arg1 = (roc_gallery)jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (roc_candidate *)jarg3; 
  arg4 = (float)jarg4; 
  result = (roc_error)roc_cluster(arg1,arg2,(struct roc_candidate const *)arg3,arg4);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_track(void * jarg1, void * jarg2, float jarg3, float jarg4) {
  char * jresult ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_time arg2 ;
  float arg3 ;
  roc_similarity arg4 ;
  roc_time *argp2 ;
  roc_error result;
  
  arg1 = (roc_gallery)jarg1; 
  argp2 = (roc_time *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null roc_time", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (float)jarg3; 
  arg4 = (roc_similarity)jarg4; 
  result = (roc_error)roc_track(arg1,arg2,arg3,arg4);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_consolidate(void * jarg1, float jarg2, unsigned long jarg3) {
  char * jresult ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_similarity arg2 ;
  size_t arg3 ;
  roc_error result;
  
  arg1 = (roc_gallery)jarg1; 
  arg2 = (roc_similarity)jarg2; 
  arg3 = (size_t)jarg3; 
  result = (roc_error)roc_consolidate(arg1,arg2,arg3);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_roc_person_ids(void * jarg1, void * jarg2) {
  char * jresult ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  roc_person_id *arg2 = (roc_person_id *) 0 ;
  roc_error result;
  
  arg1 = (roc_const_gallery)jarg1; 
  arg2 = (roc_person_id *)jarg2; 
  result = (roc_error)roc_person_ids((struct roc_gallery_type const *)arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


#ifdef __cplusplus
}
#endif

