//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum roc_algorithm_options {
  ROC_FRONTAL = 0x0000,
  ROC_FULL = 0x0001,
  ROC_PARTIAL = 0x0002,
  ROC_MANUAL = 0x0004,
  ROC_FR = 0x0010,
  ROC_ID = 0x0020,
  ROC_PITCHYAW = 0x0100,
  ROC_GENDER = 0x0200,
  ROC_AGE = 0x0400,
  ROC_OCCLUSION = 0x0800,
  ROC_LIPS = 0x1000,
  ROC_THUMBNAIL = 0x8000,
  ROC_INVALID = 0x010000,
  ROC_TEMPLATE_VERSION = (1 << 28) +(7 << 24),
  ROC_TEMPLATE_VERSION_MASK = 0x7F000000
}
