//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class rocPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="SWIGRegisterExceptionCallbacks_roc")]
    public static extern void SWIGRegisterExceptionCallbacks_roc(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_roc")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_roc(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_roc(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_roc(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(rocPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(rocPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="SWIGRegisterStringCallback_roc")]
    public static extern void SWIGRegisterStringCallback_roc(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_roc(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static rocPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_float")]
  public static extern global::System.IntPtr new_float();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_copy_float")]
  public static extern global::System.IntPtr copy_float(float jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_float")]
  public static extern void delete_float(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_float_assign")]
  public static extern void float_assign(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_float_value")]
  public static extern float float_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_uint8_t")]
  public static extern global::System.IntPtr new_uint8_t();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_copy_uint8_t")]
  public static extern global::System.IntPtr copy_uint8_t(byte jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_uint8_t")]
  public static extern void delete_uint8_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_uint8_t_assign")]
  public static extern void uint8_t_assign(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_uint8_t_value")]
  public static extern byte uint8_t_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_size_t")]
  public static extern global::System.IntPtr new_size_t();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_copy_size_t")]
  public static extern global::System.IntPtr copy_size_t(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_size_t")]
  public static extern void delete_size_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_size_t_assign")]
  public static extern void size_t_assign(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_size_t_value")]
  public static extern uint size_t_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_roc_gallery")]
  public static extern global::System.IntPtr new_roc_gallery();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_copy_roc_gallery")]
  public static extern global::System.IntPtr copy_roc_gallery(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_roc_gallery")]
  public static extern void delete_roc_gallery(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_gallery_assign")]
  public static extern void roc_gallery_assign(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_gallery_value")]
  public static extern global::System.IntPtr roc_gallery_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_roc_host_id")]
  public static extern global::System.IntPtr new_roc_host_id();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_copy_roc_host_id")]
  public static extern global::System.IntPtr copy_roc_host_id(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_roc_host_id")]
  public static extern void delete_roc_host_id(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_host_id_assign")]
  public static extern void roc_host_id_assign(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_host_id_value")]
  public static extern string roc_host_id_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_roc_similarity")]
  public static extern global::System.IntPtr new_roc_similarity();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_copy_roc_similarity")]
  public static extern global::System.IntPtr copy_roc_similarity(float jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_roc_similarity")]
  public static extern void delete_roc_similarity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_similarity_assign")]
  public static extern void roc_similarity_assign(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_similarity_value")]
  public static extern float roc_similarity_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_char_array")]
  public static extern string new_char_array(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_char_array")]
  public static extern void delete_char_array(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_char_array_getitem")]
  public static extern char char_array_getitem(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_char_array_setitem")]
  public static extern void char_array_setitem(string jarg1, int jarg2, char jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_roc_template_array")]
  public static extern global::System.IntPtr new_roc_template_array(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_roc_template_array")]
  public static extern void delete_roc_template_array(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_array_getitem")]
  public static extern global::System.IntPtr roc_template_array_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_array_setitem")]
  public static extern void roc_template_array_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_roc_similarity_array")]
  public static extern global::System.IntPtr new_roc_similarity_array(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_roc_similarity_array")]
  public static extern void delete_roc_similarity_array(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_similarity_array_getitem")]
  public static extern float roc_similarity_array_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_similarity_array_setitem")]
  public static extern void roc_similarity_array_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_roc_candidate_array")]
  public static extern global::System.IntPtr new_roc_candidate_array(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_roc_candidate_array")]
  public static extern void delete_roc_candidate_array(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_candidate_array_getitem")]
  public static extern global::System.IntPtr roc_candidate_array_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_candidate_array_setitem")]
  public static extern void roc_candidate_array_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_roc_person_id_array")]
  public static extern global::System.IntPtr new_roc_person_id_array(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_roc_person_id_array")]
  public static extern void delete_roc_person_id_array(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_person_id_array_getitem")]
  public static extern uint roc_person_id_array_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_person_id_array_setitem")]
  public static extern void roc_person_id_array_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_ROC_VERSION_MAJOR_get")]
  public static extern int ROC_VERSION_MAJOR_get();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_ROC_VERSION_MINOR_get")]
  public static extern int ROC_VERSION_MINOR_get();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_ROC_VERSION_PATCH_get")]
  public static extern int ROC_VERSION_PATCH_get();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_ROC_VERSION_STRING_get")]
  public static extern string ROC_VERSION_STRING_get();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_ensure")]
  public static extern void roc_ensure(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_initialize")]
  public static extern string roc_initialize(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_finalize")]
  public static extern string roc_finalize();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_get_host_id")]
  public static extern string roc_get_host_id(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_free_host_id")]
  public static extern string roc_free_host_id(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_image_data_set")]
  public static extern void roc_image_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_image_data_get")]
  public static extern global::System.IntPtr roc_image_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_image_width_set")]
  public static extern void roc_image_width_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_image_width_get")]
  public static extern uint roc_image_width_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_image_height_set")]
  public static extern void roc_image_height_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_image_height_get")]
  public static extern uint roc_image_height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_image_step_set")]
  public static extern void roc_image_step_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_image_step_get")]
  public static extern uint roc_image_step_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_image_color_space_set")]
  public static extern void roc_image_color_space_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_image_color_space_get")]
  public static extern int roc_image_color_space_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_roc_image")]
  public static extern global::System.IntPtr new_roc_image();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_roc_image")]
  public static extern void delete_roc_image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_free_image")]
  public static extern string roc_free_image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_read_image")]
  public static extern string roc_read_image(string jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_decode_image")]
  public static extern string roc_decode_image(uint jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_set_thumbnail_parameters")]
  public static extern string roc_set_thumbnail_parameters(int jarg1, int jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_preload")]
  public static extern string roc_preload(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_landmarks_to_face")]
  public static extern string roc_landmarks_to_face(float jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_ROC_NO_TIMESTAMP_get")]
  public static extern int ROC_NO_TIMESTAMP_get();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_ROC_UNKNOWN_PERSON_get")]
  public static extern int ROC_UNKNOWN_PERSON_get();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_algorithm_id_set")]
  public static extern void roc_template_algorithm_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_algorithm_id_get")]
  public static extern uint roc_template_algorithm_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_timestamp_set")]
  public static extern void roc_template_timestamp_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_timestamp_get")]
  public static extern global::System.IntPtr roc_template_timestamp_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_x_set")]
  public static extern void roc_template_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_x_get")]
  public static extern int roc_template_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_y_set")]
  public static extern void roc_template_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_y_get")]
  public static extern int roc_template_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_width_set")]
  public static extern void roc_template_width_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_width_get")]
  public static extern uint roc_template_width_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_height_set")]
  public static extern void roc_template_height_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_height_get")]
  public static extern uint roc_template_height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_confidence_set")]
  public static extern void roc_template_confidence_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_confidence_get")]
  public static extern float roc_template_confidence_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_person_id_set")]
  public static extern void roc_template_person_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_person_id_get")]
  public static extern uint roc_template_person_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_md_size_set")]
  public static extern void roc_template_md_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_md_size_get")]
  public static extern uint roc_template_md_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_fv_size_set")]
  public static extern void roc_template_fv_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_fv_size_get")]
  public static extern uint roc_template_fv_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_tn_size_set")]
  public static extern void roc_template_tn_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_tn_size_get")]
  public static extern uint roc_template_tn_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_md_set")]
  public static extern void roc_template_md_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_md_get")]
  public static extern string roc_template_md_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_fv_set")]
  public static extern void roc_template_fv_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_fv_get")]
  public static extern global::System.IntPtr roc_template_fv_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_tn_set")]
  public static extern void roc_template_tn_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_tn_get")]
  public static extern global::System.IntPtr roc_template_tn_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_roc_template")]
  public static extern global::System.IntPtr new_roc_template();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_roc_template")]
  public static extern void delete_roc_template(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_represent")]
  public static extern string roc_represent(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, uint jarg4, float jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_free_template")]
  public static extern string roc_free_template(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_flatten")]
  public static extern string roc_flatten(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_unflatten")]
  public static extern string roc_unflatten(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_flattened_bytes")]
  public static extern string roc_flattened_bytes(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_read_template")]
  public static extern string roc_read_template(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_read_template_fd")]
  public static extern string roc_read_template_fd(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_write_template")]
  public static extern string roc_write_template(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_write_template_fd")]
  public static extern string roc_write_template_fd(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_get_metadata")]
  public static extern string roc_get_metadata(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_set_metadata")]
  public static extern string roc_set_metadata(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_open_gallery")]
  public static extern string roc_open_gallery(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_temporary_gallery")]
  public static extern string roc_temporary_gallery(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_enroll")]
  public static extern string roc_enroll(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_size")]
  public static extern string roc_size(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_ROC_INVALID_TEMPLATE_INDEX_get")]
  public static extern uint ROC_INVALID_TEMPLATE_INDEX_get();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_at")]
  public static extern string roc_at(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_remove")]
  public static extern string roc_remove(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_close_gallery")]
  public static extern string roc_close_gallery(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_template_limit")]
  public static extern string roc_template_limit(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_compare_templates")]
  public static extern string roc_compare_templates(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_compare_galleries")]
  public static extern string roc_compare_galleries(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_candidate_index_set")]
  public static extern void roc_candidate_index_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_candidate_index_get")]
  public static extern uint roc_candidate_index_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_candidate_similarity_set")]
  public static extern void roc_candidate_similarity_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_candidate_similarity_get")]
  public static extern float roc_candidate_similarity_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_new_roc_candidate")]
  public static extern global::System.IntPtr new_roc_candidate();

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_delete_roc_candidate")]
  public static extern void delete_roc_candidate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_search")]
  public static extern string roc_search(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, float jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_knn")]
  public static extern string roc_knn(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, float jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_rerank")]
  public static extern string roc_rerank(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_cluster")]
  public static extern string roc_cluster(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_track")]
  public static extern string roc_track(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_consolidate")]
  public static extern string roc_consolidate(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("roc", EntryPoint="CSharp_roc_person_ids")]
  public static extern string roc_person_ids(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);
}
