/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class roc_algorithm_options {
  public final static int ROC_FRONTAL = rocJNI.ROC_FRONTAL_get();
  public final static int ROC_FULL = rocJNI.ROC_FULL_get();
  public final static int ROC_PARTIAL = rocJNI.ROC_PARTIAL_get();
  public final static int ROC_MANUAL = rocJNI.ROC_MANUAL_get();
  public final static int ROC_FR = rocJNI.ROC_FR_get();
  public final static int ROC_ID = rocJNI.ROC_ID_get();
  public final static int ROC_PITCHYAW = rocJNI.ROC_PITCHYAW_get();
  public final static int ROC_GENDER = rocJNI.ROC_GENDER_get();
  public final static int ROC_AGE = rocJNI.ROC_AGE_get();
  public final static int ROC_OCCLUSION = rocJNI.ROC_OCCLUSION_get();
  public final static int ROC_LIPS = rocJNI.ROC_LIPS_get();
  public final static int ROC_THUMBNAIL = rocJNI.ROC_THUMBNAIL_get();
  public final static int ROC_INVALID = rocJNI.ROC_INVALID_get();
  public final static int ROC_TEMPLATE_VERSION = rocJNI.ROC_TEMPLATE_VERSION_get();
  public final static int ROC_TEMPLATE_VERSION_MASK = rocJNI.ROC_TEMPLATE_VERSION_MASK_get();
}

