/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <stdint.h>		// Use the C99 official header


#include "roc.h"


static float *new_float() { 
  return (float *) calloc(1,sizeof(float)); 
}

static float *copy_float(float value) { 
  float *obj = (float *) calloc(1,sizeof(float));
  *obj = value;
  return obj; 
}

static void delete_float(float *obj) { 
  if (obj) free(obj); 
}

static void float_assign(float *obj, float value) {
  *obj = value;
}

static float float_value(float *obj) {
  return *obj;
}


static uint8_t *new_uint8_t() { 
  return (uint8_t *) calloc(1,sizeof(uint8_t)); 
}

static uint8_t *copy_uint8_t(uint8_t value) { 
  uint8_t *obj = (uint8_t *) calloc(1,sizeof(uint8_t));
  *obj = value;
  return obj; 
}

static void delete_uint8_t(uint8_t *obj) { 
  if (obj) free(obj); 
}

static void uint8_t_assign(uint8_t *obj, uint8_t value) {
  *obj = value;
}

static uint8_t uint8_t_value(uint8_t *obj) {
  return *obj;
}


static size_t *new_size_t() { 
  return (size_t *) calloc(1,sizeof(size_t)); 
}

static size_t *copy_size_t(size_t value) { 
  size_t *obj = (size_t *) calloc(1,sizeof(size_t));
  *obj = value;
  return obj; 
}

static void delete_size_t(size_t *obj) { 
  if (obj) free(obj); 
}

static void size_t_assign(size_t *obj, size_t value) {
  *obj = value;
}

static size_t size_t_value(size_t *obj) {
  return *obj;
}


static roc_gallery *new_roc_gallery() { 
  return (roc_gallery *) calloc(1,sizeof(roc_gallery)); 
}

static roc_gallery *copy_roc_gallery(roc_gallery value) { 
  roc_gallery *obj = (roc_gallery *) calloc(1,sizeof(roc_gallery));
  *obj = value;
  return obj; 
}

static void delete_roc_gallery(roc_gallery *obj) { 
  if (obj) free(obj); 
}

static void roc_gallery_assign(roc_gallery *obj, roc_gallery value) {
  *obj = value;
}

static roc_gallery roc_gallery_value(roc_gallery *obj) {
  return *obj;
}


static roc_host_id *new_roc_host_id() { 
  return (roc_host_id *) calloc(1,sizeof(roc_host_id)); 
}

static roc_host_id *copy_roc_host_id(roc_host_id value) { 
  roc_host_id *obj = (roc_host_id *) calloc(1,sizeof(roc_host_id));
  *obj = value;
  return obj; 
}

static void delete_roc_host_id(roc_host_id *obj) { 
  if (obj) free(obj); 
}

static void roc_host_id_assign(roc_host_id *obj, roc_host_id value) {
  *obj = value;
}

static roc_host_id roc_host_id_value(roc_host_id *obj) {
  return *obj;
}


static roc_similarity *new_roc_similarity() { 
  return (roc_similarity *) calloc(1,sizeof(roc_similarity)); 
}

static roc_similarity *copy_roc_similarity(roc_similarity value) { 
  roc_similarity *obj = (roc_similarity *) calloc(1,sizeof(roc_similarity));
  *obj = value;
  return obj; 
}

static void delete_roc_similarity(roc_similarity *obj) { 
  if (obj) free(obj); 
}

static void roc_similarity_assign(roc_similarity *obj, roc_similarity value) {
  *obj = value;
}

static roc_similarity roc_similarity_value(roc_similarity *obj) {
  return *obj;
}


static char *new_char_array(int nelements) { 
  return (char *) calloc(nelements,sizeof(char)); 
}

static void delete_char_array(char *ary) { 
  free(ary); 
}

static char char_array_getitem(char *ary, int index) {
    return ary[index];
}
static void char_array_setitem(char *ary, int index, char value) {
    ary[index] = value;
}


static roc_template *new_roc_template_array(int nelements) { 
  return (roc_template *) calloc(nelements,sizeof(roc_template)); 
}

static void delete_roc_template_array(roc_template *ary) { 
  free(ary); 
}

static roc_template roc_template_array_getitem(roc_template *ary, int index) {
    return ary[index];
}
static void roc_template_array_setitem(roc_template *ary, int index, roc_template value) {
    ary[index] = value;
}


static roc_similarity *new_roc_similarity_array(int nelements) { 
  return (roc_similarity *) calloc(nelements,sizeof(roc_similarity)); 
}

static void delete_roc_similarity_array(roc_similarity *ary) { 
  free(ary); 
}

static roc_similarity roc_similarity_array_getitem(roc_similarity *ary, int index) {
    return ary[index];
}
static void roc_similarity_array_setitem(roc_similarity *ary, int index, roc_similarity value) {
    ary[index] = value;
}


static roc_candidate *new_roc_candidate_array(int nelements) { 
  return (roc_candidate *) calloc(nelements,sizeof(roc_candidate)); 
}

static void delete_roc_candidate_array(roc_candidate *ary) { 
  free(ary); 
}

static roc_candidate roc_candidate_array_getitem(roc_candidate *ary, int index) {
    return ary[index];
}
static void roc_candidate_array_setitem(roc_candidate *ary, int index, roc_candidate value) {
    ary[index] = value;
}


static roc_person_id *new_roc_person_id_array(int nelements) { 
  return (roc_person_id *) calloc(nelements,sizeof(roc_person_id)); 
}

static void delete_roc_person_id_array(roc_person_id *ary) { 
  free(ary); 
}

static roc_person_id roc_person_id_array_getitem(roc_person_id *ary, int index) {
    return ary[index];
}
static void roc_person_id_array_setitem(roc_person_id *ary, int index, roc_person_id value) {
    ary[index] = value;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_rocJNI_new_1float(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (float *)new_float();
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_copy_1float(JNIEnv *jenv, jclass jcls, jfloat jarg1) {
  jlong jresult = 0 ;
  float arg1 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  result = (float *)copy_float(arg1);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1float(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  float *arg1 = (float *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(float **)&jarg1; 
  delete_float(arg1);
}


SWIGEXPORT void JNICALL Java_rocJNI_float_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  float *arg1 = (float *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(float **)&jarg1; 
  arg2 = (float)jarg2; 
  float_assign(arg1,arg2);
}


SWIGEXPORT jfloat JNICALL Java_rocJNI_float_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jfloat jresult = 0 ;
  float *arg1 = (float *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(float **)&jarg1; 
  result = (float)float_value(arg1);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1uint8_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (uint8_t *)new_uint8_t();
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_copy_1uint8_1t(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  jlong jresult = 0 ;
  uint8_t arg1 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (uint8_t)jarg1; 
  result = (uint8_t *)copy_uint8_t(arg1);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1uint8_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  uint8_t *arg1 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(uint8_t **)&jarg1; 
  delete_uint8_t(arg1);
}


SWIGEXPORT void JNICALL Java_rocJNI_uint8_1t_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2) {
  uint8_t *arg1 = (uint8_t *) 0 ;
  uint8_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(uint8_t **)&jarg1; 
  arg2 = (uint8_t)jarg2; 
  uint8_t_assign(arg1,arg2);
}


SWIGEXPORT jshort JNICALL Java_rocJNI_uint8_1t_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(uint8_t **)&jarg1; 
  result = (uint8_t)uint8_t_value(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1size_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  size_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (size_t *)new_size_t();
  *(size_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_copy_1size_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t arg1 ;
  size_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  result = (size_t *)copy_size_t(arg1);
  *(size_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1size_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  size_t *arg1 = (size_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(size_t **)&jarg1; 
  delete_size_t(arg1);
}


SWIGEXPORT void JNICALL Java_rocJNI_size_1t_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  size_t *arg1 = (size_t *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(size_t **)&jarg1; 
  arg2 = (size_t)jarg2; 
  size_t_assign(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_rocJNI_size_1t_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t *arg1 = (size_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(size_t **)&jarg1; 
  result = size_t_value(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1roc_1gallery(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  roc_gallery *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (roc_gallery *)new_roc_gallery();
  *(roc_gallery **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_copy_1roc_1gallery(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_gallery *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_gallery *)&jarg1; 
  result = (roc_gallery *)copy_roc_gallery(arg1);
  *(roc_gallery **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1roc_1gallery(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  roc_gallery *arg1 = (roc_gallery *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_gallery **)&jarg1; 
  delete_roc_gallery(arg1);
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1gallery_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  roc_gallery *arg1 = (roc_gallery *) 0 ;
  roc_gallery arg2 = (roc_gallery) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_gallery **)&jarg1; 
  arg2 = *(roc_gallery *)&jarg2; 
  roc_gallery_assign(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1gallery_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  roc_gallery *arg1 = (roc_gallery *) 0 ;
  roc_gallery result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_gallery **)&jarg1; 
  result = (roc_gallery)roc_gallery_value(arg1);
  *(roc_gallery *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1roc_1host_1id(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  roc_host_id *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (roc_host_id *)new_roc_host_id();
  *(roc_host_id **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_copy_1roc_1host_1id(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  roc_host_id arg1 = (roc_host_id) 0 ;
  roc_host_id *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (roc_host_id)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (roc_host_id *)copy_roc_host_id((char const *)arg1);
  *(roc_host_id **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1roc_1host_1id(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  roc_host_id *arg1 = (roc_host_id *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_host_id **)&jarg1; 
  delete_roc_host_id((char const **)arg1);
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1host_1id_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  roc_host_id *arg1 = (roc_host_id *) 0 ;
  roc_host_id arg2 = (roc_host_id) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_host_id **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (roc_host_id)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  roc_host_id_assign((char const **)arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1host_1id_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  roc_host_id *arg1 = (roc_host_id *) 0 ;
  roc_host_id result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_host_id **)&jarg1; 
  result = (roc_host_id)roc_host_id_value((char const **)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1roc_1similarity(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  roc_similarity *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (roc_similarity *)new_roc_similarity();
  *(roc_similarity **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_copy_1roc_1similarity(JNIEnv *jenv, jclass jcls, jfloat jarg1) {
  jlong jresult = 0 ;
  roc_similarity arg1 ;
  roc_similarity *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (roc_similarity)jarg1; 
  result = (roc_similarity *)copy_roc_similarity(arg1);
  *(roc_similarity **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1roc_1similarity(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_similarity **)&jarg1; 
  delete_roc_similarity(arg1);
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1similarity_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  roc_similarity arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_similarity **)&jarg1; 
  arg2 = (roc_similarity)jarg2; 
  roc_similarity_assign(arg1,arg2);
}


SWIGEXPORT jfloat JNICALL Java_rocJNI_roc_1similarity_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jfloat jresult = 0 ;
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  roc_similarity result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_similarity **)&jarg1; 
  result = (roc_similarity)roc_similarity_value(arg1);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_new_1char_1array(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jstring jresult = 0 ;
  int arg1 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (char *)new_char_array(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1char_1array(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  delete_char_array(arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jchar JNICALL Java_rocJNI_char_1array_1getitem(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2) {
  jchar jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int arg2 ;
  char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (int)jarg2; 
  result = (char)char_array_getitem(arg1,arg2);
  jresult = (jchar)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_char_1array_1setitem(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jchar jarg3) {
  char *arg1 = (char *) 0 ;
  int arg2 ;
  char arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  arg2 = (int)jarg2; 
  arg3 = (char)jarg3; 
  char_array_setitem(arg1,arg2,arg3);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1roc_1template_1array(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  roc_template *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (roc_template *)new_roc_template_array(arg1);
  *(roc_template **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1roc_1template_1array(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  roc_template *arg1 = (roc_template *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(roc_template **)&jarg1; 
  delete_roc_template_array(arg1);
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1array_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  roc_template *arg1 = (roc_template *) 0 ;
  int arg2 ;
  roc_template result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(roc_template **)&jarg1; 
  arg2 = (int)jarg2; 
  result = roc_template_array_getitem(arg1,arg2);
  {
    roc_template * resultptr = (roc_template *) malloc(sizeof(roc_template));
    memmove(resultptr, &result, sizeof(roc_template));
    *(roc_template **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1array_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  roc_template *arg1 = (roc_template *) 0 ;
  int arg2 ;
  roc_template arg3 ;
  roc_template *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(roc_template **)&jarg1; 
  arg2 = (int)jarg2; 
  argp3 = *(roc_template **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_template");
    return ;
  }
  arg3 = *argp3; 
  roc_template_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1roc_1similarity_1array(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  roc_similarity *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (roc_similarity *)new_roc_similarity_array(arg1);
  *(roc_similarity **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1roc_1similarity_1array(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_similarity **)&jarg1; 
  delete_roc_similarity_array(arg1);
}


SWIGEXPORT jfloat JNICALL Java_rocJNI_roc_1similarity_1array_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jfloat jresult = 0 ;
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  int arg2 ;
  roc_similarity result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_similarity **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (roc_similarity)roc_similarity_array_getitem(arg1,arg2);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1similarity_1array_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jfloat jarg3) {
  roc_similarity *arg1 = (roc_similarity *) 0 ;
  int arg2 ;
  roc_similarity arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_similarity **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (roc_similarity)jarg3; 
  roc_similarity_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1roc_1candidate_1array(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  roc_candidate *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (roc_candidate *)new_roc_candidate_array(arg1);
  *(roc_candidate **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1roc_1candidate_1array(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  roc_candidate *arg1 = (roc_candidate *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(roc_candidate **)&jarg1; 
  delete_roc_candidate_array(arg1);
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1candidate_1array_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  roc_candidate *arg1 = (roc_candidate *) 0 ;
  int arg2 ;
  roc_candidate result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(roc_candidate **)&jarg1; 
  arg2 = (int)jarg2; 
  result = roc_candidate_array_getitem(arg1,arg2);
  {
    roc_candidate * resultptr = (roc_candidate *) malloc(sizeof(roc_candidate));
    memmove(resultptr, &result, sizeof(roc_candidate));
    *(roc_candidate **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1candidate_1array_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  roc_candidate *arg1 = (roc_candidate *) 0 ;
  int arg2 ;
  roc_candidate arg3 ;
  roc_candidate *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(roc_candidate **)&jarg1; 
  arg2 = (int)jarg2; 
  argp3 = *(roc_candidate **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_candidate");
    return ;
  }
  arg3 = *argp3; 
  roc_candidate_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1roc_1person_1id_1array(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  roc_person_id *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (roc_person_id *)new_roc_person_id_array(arg1);
  *(roc_person_id **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1roc_1person_1id_1array(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  roc_person_id *arg1 = (roc_person_id *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_person_id **)&jarg1; 
  delete_roc_person_id_array(arg1);
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1person_1id_1array_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  roc_person_id *arg1 = (roc_person_id *) 0 ;
  int arg2 ;
  roc_person_id result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_person_id **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (roc_person_id)roc_person_id_array_getitem(arg1,arg2);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1person_1id_1array_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  roc_person_id *arg1 = (roc_person_id *) 0 ;
  int arg2 ;
  roc_person_id arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_person_id **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (roc_person_id)jarg3; 
  roc_person_id_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1VERSION_1MAJOR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1VERSION_1MINOR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1VERSION_1PATCH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_ROC_1VERSION_1STRING_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)("1.7.0");
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1ensure(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  roc_error arg1 = (roc_error) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (roc_error)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  roc_ensure((char const *)arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1initialize(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (roc_error)roc_initialize((char const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1finalize(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  result = (roc_error)roc_finalize();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1get_1host_1id(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  roc_host_id *arg1 = (roc_host_id *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_host_id **)&jarg1; 
  result = (roc_error)roc_get_host_id((char const **)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1free_1host_1id(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jstring jresult = 0 ;
  roc_host_id arg1 = (roc_host_id) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (roc_host_id)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (roc_error)roc_free_host_id((char const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1GRAY8_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_color_space result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_color_space)ROC_GRAY8;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1BGR24_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_color_space result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_color_space)ROC_BGR24;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1image_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_image **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1image_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_image **)&jarg1; 
  result = (uint8_t *) ((arg1)->data);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1image_1width_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_image **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->width = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1image_1width_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_image **)&jarg1; 
  result =  ((arg1)->width);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1image_1height_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_image **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->height = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1image_1height_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_image **)&jarg1; 
  result =  ((arg1)->height);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1image_1step_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_image **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->step = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1image_1step_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_image **)&jarg1; 
  result =  ((arg1)->step);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1image_1color_1space_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  roc_color_space arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_image **)&jarg1; 
  arg2 = (roc_color_space)jarg2; 
  if (arg1) (arg1)->color_space = arg2;
}


SWIGEXPORT jint JNICALL Java_rocJNI_roc_1image_1color_1space_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  roc_color_space result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_image **)&jarg1; 
  result = (roc_color_space) ((arg1)->color_space);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1roc_1image(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct roc_image *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct roc_image *)calloc(1, sizeof(struct roc_image));
  *(struct roc_image **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1roc_1image(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct roc_image *arg1 = (struct roc_image *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct roc_image **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1free_1image(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  roc_image arg1 ;
  roc_image *argp1 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(roc_image **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_image");
    return 0;
  }
  arg1 = *argp1; 
  result = (roc_error)roc_free_image(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1read_1image(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jlong jarg3, jobject jarg3_) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  roc_color_space arg2 ;
  roc_image *arg3 = (roc_image *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (roc_color_space)jarg2; 
  arg3 = *(roc_image **)&jarg3; 
  result = (roc_error)roc_read_image((char const *)arg1,arg2,arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1decode_1image(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jobject jarg4_) {
  jstring jresult = 0 ;
  size_t arg1 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  roc_color_space arg3 ;
  roc_image *arg4 = (roc_image *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  arg1 = (size_t)jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  arg3 = (roc_color_space)jarg3; 
  arg4 = *(roc_image **)&jarg4; 
  result = (roc_error)roc_decode_image(arg1,(unsigned char const *)arg2,arg3,arg4);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1set_1thumbnail_1parameters(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jfloat jarg3, jfloat jarg4) {
  jstring jresult = 0 ;
  int arg1 ;
  int arg2 ;
  float arg3 ;
  float arg4 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  result = (roc_error)roc_set_thumbnail_parameters(arg1,arg2,arg3,arg4);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1FRONTAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_FRONTAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1FULL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_FULL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1PARTIAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_PARTIAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1MANUAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_MANUAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1FR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_FR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1ID_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_ID;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1PITCHYAW_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_PITCHYAW;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1GENDER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_GENDER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1AGE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_AGE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1OCCLUSION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_OCCLUSION;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1LIPS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_LIPS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1THUMBNAIL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_THUMBNAIL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1INVALID_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_INVALID;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1TEMPLATE_1VERSION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_TEMPLATE_VERSION;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1TEMPLATE_1VERSION_1MASK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum roc_algorithm_options result;
  
  (void)jenv;
  (void)jcls;
  result = (enum roc_algorithm_options)ROC_TEMPLATE_VERSION_MASK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1preload(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  roc_algorithm_id arg1 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (roc_algorithm_id)jarg1; 
  result = (roc_error)roc_preload(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1landmarks_1to_1face(JNIEnv *jenv, jclass jcls, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jfloat jarg5, jfloat jarg6, jlong jarg7, jlong jarg8, jlong jarg9, jlong jarg10) {
  jstring jresult = 0 ;
  float arg1 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  float arg6 ;
  float *arg7 = (float *) 0 ;
  float *arg8 = (float *) 0 ;
  float *arg9 = (float *) 0 ;
  float *arg10 = (float *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  arg5 = (float)jarg5; 
  arg6 = (float)jarg6; 
  arg7 = *(float **)&jarg7; 
  arg8 = *(float **)&jarg8; 
  arg9 = *(float **)&jarg9; 
  arg10 = *(float **)&jarg10; 
  result = (roc_error)roc_landmarks_to_face(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1NO_1TIMESTAMP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0xFFFFFFFF);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_rocJNI_ROC_1UNKNOWN_1PERSON_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0xFFFFFFFF);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1algorithm_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_algorithm_id arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = (roc_algorithm_id)jarg2; 
  if (arg1) (arg1)->algorithm_id = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1algorithm_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_algorithm_id result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (roc_algorithm_id) ((arg1)->algorithm_id);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1timestamp_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_time arg2 ;
  roc_time *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  argp2 = *(roc_time **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_time");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->timestamp = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1timestamp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_time result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result =  ((arg1)->timestamp);
  {
    roc_time * resultptr = (roc_time *) malloc(sizeof(roc_time));
    memmove(resultptr, &result, sizeof(roc_time));
    *(roc_time **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1x_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  int32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = (int32_t)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT jint JNICALL Java_rocJNI_roc_1template_1x_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  int32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (int32_t) ((arg1)->x);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1y_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  int32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = (int32_t)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT jint JNICALL Java_rocJNI_roc_1template_1y_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  int32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (int32_t) ((arg1)->y);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1width_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->width = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1width_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (uint32_t) ((arg1)->width);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1height_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->height = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1height_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (uint32_t) ((arg1)->height);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1confidence_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->confidence = arg2;
}


SWIGEXPORT jfloat JNICALL Java_rocJNI_roc_1template_1confidence_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (float) ((arg1)->confidence);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1person_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_person_id arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = (roc_person_id)jarg2; 
  if (arg1) (arg1)->person_id = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1person_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  roc_person_id result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (roc_person_id) ((arg1)->person_id);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1md_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->md_size = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1md_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (uint32_t) ((arg1)->md_size);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1fv_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->fv_size = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1fv_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (uint32_t) ((arg1)->fv_size);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1tn_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->tn_size = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1tn_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (uint32_t) ((arg1)->tn_size);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1md_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->md = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->md, (const char *)arg2);
    } else {
      arg1->md = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1template_1md_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (char *) ((arg1)->md);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1fv_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->fv = (uint8_t const *)arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1fv_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (uint8_t *) ((arg1)->fv);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1template_1tn_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  if (arg1) (arg1)->tn = (uint8_t const *)arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1template_1tn_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_template **)&jarg1; 
  result = (uint8_t *) ((arg1)->tn);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1roc_1template(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct roc_template *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct roc_template *)calloc(1, sizeof(struct roc_template));
  *(struct roc_template **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1roc_1template(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct roc_template *arg1 = (struct roc_template *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct roc_template **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1represent(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4, jfloat jarg5, jlong jarg6, jobject jarg6_) {
  jstring jresult = 0 ;
  roc_image arg1 ;
  roc_algorithm_id arg2 ;
  size_t arg3 ;
  size_t arg4 ;
  float arg5 ;
  roc_template *arg6 = (roc_template *) 0 ;
  roc_image *argp1 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg6_;
  argp1 = *(roc_image **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_image");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (roc_algorithm_id)jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (size_t)jarg4; 
  arg5 = (float)jarg5; 
  arg6 = *(roc_template **)&jarg6; 
  result = (roc_error)roc_represent(arg1,arg2,arg3,arg4,arg5,arg6);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1free_1template(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  roc_template *arg1 = (roc_template *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(roc_template **)&jarg1; 
  result = (roc_error)roc_free_template(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1flatten(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jstring jresult = 0 ;
  roc_template arg1 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  roc_template const *argp1 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(roc_template **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_template const");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = *(uint8_t **)&jarg2; 
  result = (roc_error)roc_flatten(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1unflatten(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jstring jresult = 0 ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  roc_template *arg2 = (roc_template *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(uint8_t **)&jarg1; 
  arg2 = *(roc_template **)&jarg2; 
  result = (roc_error)roc_unflatten((unsigned char const *)arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1flattened_1bytes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jstring jresult = 0 ;
  roc_template arg1 ;
  size_t *arg2 = (size_t *) 0 ;
  roc_template const *argp1 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(roc_template **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_template const");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = *(size_t **)&jarg2; 
  result = (roc_error)roc_flattened_bytes(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1read_1template(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jstring jresult = 0 ;
  FILE *arg1 = (FILE *) 0 ;
  roc_template *arg2 = (roc_template *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(roc_template **)&jarg2; 
  result = (roc_error)roc_read_template(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1read_1template_1fd(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_) {
  jstring jresult = 0 ;
  int arg1 ;
  roc_template *arg2 = (roc_template *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (int)jarg1; 
  arg2 = *(roc_template **)&jarg2; 
  result = (roc_error)roc_read_template_fd(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1write_1template(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jstring jresult = 0 ;
  FILE *arg1 = (FILE *) 0 ;
  roc_template arg2 ;
  roc_template const *argp2 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(FILE **)&jarg1; 
  argp2 = *(roc_template **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_template const");
    return 0;
  }
  arg2 = *argp2; 
  result = (roc_error)roc_write_template(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1write_1template_1fd(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_) {
  jstring jresult = 0 ;
  int arg1 ;
  roc_template arg2 ;
  roc_template const *argp2 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (int)jarg1; 
  argp2 = *(roc_template **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_template const");
    return 0;
  }
  arg2 = *argp2; 
  result = (roc_error)roc_write_template_fd(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1get_1metadata(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jlong jarg4) {
  jstring jresult = 0 ;
  roc_template arg1 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  size_t arg4 ;
  roc_template const *argp1 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(roc_template **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_template const");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (size_t)jarg4; 
  result = (roc_error)roc_get_metadata(arg1,(char const *)arg2,arg3,arg4);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1set_1metadata(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3) {
  jstring jresult = 0 ;
  roc_template *arg1 = (roc_template *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(roc_template **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (roc_error)roc_set_metadata(arg1,(char const *)arg2,(char const *)arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1open_1gallery(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3) {
  jstring jresult = 0 ;
  roc_gallery_file arg1 = (roc_gallery_file) 0 ;
  roc_gallery *arg2 = (roc_gallery *) 0 ;
  roc_progress arg3 = (roc_progress) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (roc_gallery_file)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(roc_gallery **)&jarg2; 
  arg3 = *(roc_progress *)&jarg3; 
  result = (roc_error)roc_open_gallery((char const *)arg1,arg2,arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1temporary_1gallery(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  roc_gallery *arg1 = (roc_gallery *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_gallery **)&jarg1; 
  result = (roc_error)roc_temporary_gallery(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1enroll(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jstring jresult = 0 ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_template arg2 ;
  roc_template const *argp2 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(roc_gallery *)&jarg1; 
  argp2 = *(roc_template **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_template const");
    return 0;
  }
  arg2 = *argp2; 
  result = (roc_error)roc_enroll(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jstring jresult = 0 ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  size_t *arg2 = (size_t *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_const_gallery *)&jarg1; 
  arg2 = *(size_t **)&jarg2; 
  result = (roc_error)roc_size((struct roc_gallery_type const *)arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_ROC_1INVALID_1TEMPLATE_1INDEX_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  result = (size_t)ROC_INVALID_TEMPLATE_INDEX;
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1at(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_) {
  jstring jresult = 0 ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  roc_template_index arg2 ;
  roc_template *arg3 = (roc_template *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(roc_const_gallery *)&jarg1; 
  arg2 = (roc_template_index)jarg2; 
  arg3 = *(roc_template **)&jarg3; 
  result = (roc_error)roc_at((struct roc_gallery_type const *)arg1,arg2,arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1remove(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jstring jresult = 0 ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_template_index arg2 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_gallery *)&jarg1; 
  arg2 = (roc_template_index)jarg2; 
  result = (roc_error)roc_remove(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1close_1gallery(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_gallery *)&jarg1; 
  result = (roc_error)roc_close_gallery(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1template_1limit(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  size_t *arg1 = (size_t *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(size_t **)&jarg1; 
  result = (roc_error)roc_template_limit(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1compare_1templates(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3) {
  jstring jresult = 0 ;
  roc_template arg1 ;
  roc_template arg2 ;
  roc_similarity *arg3 = (roc_similarity *) 0 ;
  roc_template const *argp1 ;
  roc_template const *argp2 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  argp1 = *(roc_template **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_template const");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(roc_template **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_template const");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(roc_similarity **)&jarg3; 
  result = (roc_error)roc_compare_templates(arg1,arg2,arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1compare_1galleries(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jstring jresult = 0 ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  roc_const_gallery arg2 = (roc_const_gallery) 0 ;
  roc_similarity *arg3 = (roc_similarity *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_const_gallery *)&jarg1; 
  arg2 = *(roc_const_gallery *)&jarg2; 
  arg3 = *(roc_similarity **)&jarg3; 
  result = (roc_error)roc_compare_galleries((struct roc_gallery_type const *)arg1,(struct roc_gallery_type const *)arg2,arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1candidate_1index_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct roc_candidate *arg1 = (struct roc_candidate *) 0 ;
  roc_template_index arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_candidate **)&jarg1; 
  arg2 = (roc_template_index)jarg2; 
  if (arg1) (arg1)->index = arg2;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_roc_1candidate_1index_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct roc_candidate *arg1 = (struct roc_candidate *) 0 ;
  roc_template_index result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_candidate **)&jarg1; 
  result =  ((arg1)->index);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_roc_1candidate_1similarity_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct roc_candidate *arg1 = (struct roc_candidate *) 0 ;
  roc_similarity arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_candidate **)&jarg1; 
  arg2 = (roc_similarity)jarg2; 
  if (arg1) (arg1)->similarity = arg2;
}


SWIGEXPORT jfloat JNICALL Java_rocJNI_roc_1candidate_1similarity_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct roc_candidate *arg1 = (struct roc_candidate *) 0 ;
  roc_similarity result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct roc_candidate **)&jarg1; 
  result = (roc_similarity) ((arg1)->similarity);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rocJNI_new_1roc_1candidate(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct roc_candidate *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct roc_candidate *)calloc(1, sizeof(struct roc_candidate));
  *(struct roc_candidate **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rocJNI_delete_1roc_1candidate(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct roc_candidate *arg1 = (struct roc_candidate *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct roc_candidate **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1search(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_, jlong jarg3, jfloat jarg4, jlong jarg5, jobject jarg5_) {
  jstring jresult = 0 ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  roc_template arg2 ;
  size_t arg3 ;
  roc_similarity arg4 ;
  roc_candidate *arg5 = (roc_candidate *) 0 ;
  roc_template const *argp2 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  (void)jarg5_;
  arg1 = *(roc_const_gallery *)&jarg1; 
  argp2 = *(roc_template **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_template const");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (size_t)jarg3; 
  arg4 = (roc_similarity)jarg4; 
  arg5 = *(roc_candidate **)&jarg5; 
  result = (roc_error)roc_search((struct roc_gallery_type const *)arg1,arg2,arg3,arg4,arg5);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1knn(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jfloat jarg4, jlong jarg5, jobject jarg5_) {
  jstring jresult = 0 ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  roc_const_gallery arg2 = (roc_const_gallery) 0 ;
  size_t arg3 ;
  roc_similarity arg4 ;
  roc_candidate *arg5 = (roc_candidate *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  arg1 = *(roc_const_gallery *)&jarg1; 
  arg2 = *(roc_const_gallery *)&jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (roc_similarity)jarg4; 
  arg5 = *(roc_candidate **)&jarg5; 
  result = (roc_error)roc_knn((struct roc_gallery_type const *)arg1,(struct roc_gallery_type const *)arg2,arg3,arg4,arg5);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1rerank(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_) {
  jstring jresult = 0 ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  size_t arg2 ;
  roc_candidate *arg3 = (roc_candidate *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(roc_const_gallery *)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = *(roc_candidate **)&jarg3; 
  result = (roc_error)roc_rerank((struct roc_gallery_type const *)arg1,arg2,arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1cluster(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_, jfloat jarg4) {
  jstring jresult = 0 ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  size_t arg2 ;
  roc_candidate *arg3 = (roc_candidate *) 0 ;
  float arg4 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(roc_gallery *)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = *(roc_candidate **)&jarg3; 
  arg4 = (float)jarg4; 
  result = (roc_error)roc_cluster(arg1,arg2,(struct roc_candidate const *)arg3,arg4);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1track(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloat jarg3, jfloat jarg4) {
  jstring jresult = 0 ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_time arg2 ;
  float arg3 ;
  roc_similarity arg4 ;
  roc_time *argp2 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_gallery *)&jarg1; 
  argp2 = *(roc_time **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null roc_time");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (float)jarg3; 
  arg4 = (roc_similarity)jarg4; 
  result = (roc_error)roc_track(arg1,arg2,arg3,arg4);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1consolidate(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2, jlong jarg3) {
  jstring jresult = 0 ;
  roc_gallery arg1 = (roc_gallery) 0 ;
  roc_similarity arg2 ;
  size_t arg3 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_gallery *)&jarg1; 
  arg2 = (roc_similarity)jarg2; 
  arg3 = (size_t)jarg3; 
  result = (roc_error)roc_consolidate(arg1,arg2,arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_rocJNI_roc_1person_1ids(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jstring jresult = 0 ;
  roc_const_gallery arg1 = (roc_const_gallery) 0 ;
  roc_person_id *arg2 = (roc_person_id *) 0 ;
  roc_error result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(roc_const_gallery *)&jarg1; 
  arg2 = *(roc_person_id **)&jarg2; 
  result = (roc_error)roc_person_ids((struct roc_gallery_type const *)arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


#ifdef __cplusplus
}
#endif

