/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface rocConstants {
  public final static int ROC_VERSION_MAJOR = rocJNI.ROC_VERSION_MAJOR_get();
  public final static int ROC_VERSION_MINOR = rocJNI.ROC_VERSION_MINOR_get();
  public final static int ROC_VERSION_PATCH = rocJNI.ROC_VERSION_PATCH_get();
  public final static String ROC_VERSION_STRING = rocJNI.ROC_VERSION_STRING_get();
  public final static int ROC_NO_TIMESTAMP = rocJNI.ROC_NO_TIMESTAMP_get();
  public final static int ROC_UNKNOWN_PERSON = rocJNI.ROC_UNKNOWN_PERSON_get();
}
